package com.aionemu.gameserver.services.ai.combat;

public enum CombatStatus {
	IDLE,
	HIT_STARTED,
	ASSIST_DISABLED,
	DUPLICATE_EVENT,
	EVENT_EXPIRED,
	SESSION_MISMATCH,
	ROLE_MISMATCH,
	TARGET_NOT_ALLOWED,
	TARGET_NOT_HOSTILE,
	TARGET_NOT_KNOWN,
	TARGET_NOT_VISIBLE,
	MAP_OR_INSTANCE_MISMATCH,
	OUT_OF_RANGE,
	NO_LINE_OF_SIGHT,
	TARGET_DEAD,
	TARGET_UNSPAWNED,
	TARGET_INVULNERABLE,
	COMPANION_DEAD,
	UNSAFE_EQUIPMENT,
	COOLDOWN,
	REMOVING,
	RUNTIME_DISABLED,
	REJECTED_BY_PLAYER_RULES
}
