package com.aionemu.gameserver.services.ai.combat;

public enum CombatPreflightViolation {
	RUNTIME_DISABLED,
	REMOVING,
	ASSIST_DISABLED,
	SESSION_MISMATCH,
	ROLE_MISMATCH,
	EVENT_EXPIRED,
	TARGET_NOT_NPC,
	TARGET_NOT_ALLOWED,
	TARGET_UNSUPPORTED,
	TARGET_UNSPAWNED,
	TARGET_DEAD,
	TARGET_INVULNERABLE,
	TARGET_NOT_HOSTILE,
	MAP_OR_INSTANCE_MISMATCH,
	TARGET_NOT_KNOWN,
	TARGET_NOT_VISIBLE,
	OUT_OF_RANGE,
	NO_LINE_OF_SIGHT,
	COMPANION_DEAD,
	UNSAFE_EQUIPMENT,
	COOLDOWN
}
