database.url = jdbc:mysql://aion-mysql:3306/aion_ls?serverTimezone=UTC&characterEncoding=UTF-8
database.user = root
database.password =

loginserver.network.client.socket_address = 0.0.0.0:2106
loginserver.network.gameserver.socket_address = 0.0.0.0:9014
loginserver.accounts.autocreate = true

